- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars: 
    homebrew_packages:
      - curl
      - jq
      - openssl
      - python
      - tree
      - wget
      - zsh
  tasks:
      - name: Install brew packages
        homebrew: name={{ item }}
        with_items: homebrew_packages


