- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars: 
    homebrew_packages:
     - curl
     - jq
     - openssl
     - python
     - tree
     - wget
     - zsh
  tasks:
     - name: Install brew packages
       homebrew: name={{ item }}
       with_items: homebrew_packages

     - name: Instakk oh-my-zsh
       shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
